bin: add code to check for dependency availability

diff --git a/.local/bin/brightness b/.local/bin/brightness
--- a/.local/bin/brightness
+++ b/.local/bin/brightness
@@ -6,7 +6,7 @@ set -e
 app_name=${0##*/}
 lock_file=${XDG_RUNTIME_DIR-/tmp}/.$app_name.lock
 nid_file=${XDG_RUNTIME_DIR-/tmp}/.$app_name.bin.nid
-notify=false
+should_notify=false
 
 true()  { return 0; }
 false() { ! true;   }
@@ -14,6 +14,24 @@ false() { ! true;   }
 usage() {
   echo "Usage: $app_name [-h] [--notify] [+|-]<val>[%]"
   exit "${1-0}"
+}
+notify() {
+  notify-send.sh \
+    --urgency normal \
+    --expire-time 3000 \
+    --app-name "$app_name" \
+    --icon notification-display-brightness \
+    --replace-file "$nid_file" \
+    "$@"
+}
+check_avail() {
+  if ! command -v "$1" >/dev/null; then
+    echo >&2 "Missing dependency: $1"
+    $should_notify && notify "Missing dependency: $1"
+    false
+  else
+    true
+  fi
 }
 
 min() { [ "$1" -lt "$2" ] && echo "$1" || echo "$2"; }
@@ -33,7 +51,7 @@ touch "$lock_file" && trap 'rm -f "$lock_file"' EXIT HUP INT TERM
 
 while [ -n "$1" ]; do
   case $1 in
-    --notify) notify=true ;;
+    --notify) should_notify=true ;;
     -h) usage ;;
      *) break ;;
   esac
@@ -41,6 +59,7 @@ while [ -n "$1" ]; do
 done
 
 [ $# -gt 0 ] || usage 1
+check_avail brightnessctl || exit 1
 
 val=${1#[-+]}
 val=${val%\%}
@@ -53,7 +72,7 @@ case $1 in
 esac
 set_brightness "$new"
 
-$notify || exit 0
+$should_notify || exit 0
 
 icon=notification-display-brightness
 case $new in
@@ -63,11 +82,8 @@ case $new in
   [8-9][0-9]|100)   urgency=critical icon=$icon-full   ;;
 esac
 
-notify-send.sh \
-  --urgency $urgency \
-  --app-name "$app_name" \
+notify \
   --icon $icon \
-  --expire-time 3000 \
-  --replace-file "$nid_file" \
+  --urgency $urgency \
   --hint "int:value:$new" \
   "Brightness: $new%"
diff --git a/.local/bin/toggle-touchpad b/.local/bin/toggle-touchpad
--- a/.local/bin/toggle-touchpad
+++ b/.local/bin/toggle-touchpad
@@ -8,9 +8,9 @@
 set -e
 
 app_name=${0##*/}
-file=${XDG_CACHE_HOME-$HOME/.cache}/touchpad-status
+cache_file=${XDG_CACHE_HOME-$HOME/.cache}/touchpad-status
 nid_file=${XDG_RUNTIME_DIR-/tmp}/.$app_name.bin.nid
-notify=false
+should_notify=false
 
 true()  { return 0; }
 false() { ! true;   }
@@ -21,10 +21,28 @@ usage() {
   echo "Usage: $app_name [-h] [--notify]"
   exit "$err"
 }
+notify() {
+  notify-send.sh \
+    --urgency normal \
+    --expire-time 3000 \
+    --app-name "$app_name" \
+    --icon input-touchpad \
+    --replace-file "$nid_file" \
+    "$@"
+}
+check_avail() {
+  if ! command -v "$1" >/dev/null; then
+    echo >&2 "Missing dependency: $1"
+    $should_notify && notify "Missing dependency: $1"
+    false
+  else
+    true
+  fi
+}
 
 while [ -n "$1" ]; do
   case $1 in
-    --notify) notify=true ;;
+    --notify) should_notify=true ;;
     -h) usage ;;
      *) break ;;
   esac
@@ -32,11 +50,17 @@ while [ -n "$1" ]; do
 done
 
 [ $# -gt 0 ] && usage 1
-
-if [ -f "$file" ]; then
-  read -r status < "$file"
+if [ -n "$SWAYSOCK" ]; then
+  check_avail swaymsg || exit 1
+  check_avail jq || exit 1
 else
-  mkdir -p "${file%/*}"
+  check_avail xinput || exit 1
+fi
+
+if [ -f "$cache_file" ]; then
+  read -r status < "$cache_file"
+else
+  mkdir -p "${cache_file%/*}"
   if [ -n "$SWAYSOCK" ]; then
     evs=$(swaymsg -t get_inputs |
       jq -r 'first(.[], select(.type=="touchpad")).libinput.send_events')
@@ -59,24 +83,18 @@ else
   xinput set-prop "$tpid" "$setting" $new
 fi
 
-echo $new > "$file"
+echo $new > "$cache_file"
 
-$notify || exit 0
+$should_notify || exit 0
 
 if [ $new -eq 0 ]; then
-  urgency=low
-  icon=input-touchpad-off
-  summary="Touchpad Disabled"
+  notify \
+    --urgency low \
+    --icon input-touchpad-off \
+    "Touchpad Disabled"
 else
-  urgency=normal
-  icon=input-touchpad-on
-  summary="Touchpad Enabled"
+  notify \
+    --urgency normal \
+    --icon input-touchpad-on \
+    "Touchpad Enabled"
 fi
-
-notify-send.sh \
-  --app-name "$app_name" \
-  --urgency $urgency \
-  --expire-time 3000 \
-  --icon $icon \
-  --replace-file "$nid_file" \
-  "$summary"
diff --git a/.local/bin/volume b/.local/bin/volume
--- a/.local/bin/volume
+++ b/.local/bin/volume
@@ -10,7 +10,8 @@ set -e
 app_name=${0##*/}
 lock_file=${XDG_RUNTIME_DIR-/tmp}/.$app_name.lock
 nid_file=${XDG_RUNTIME_DIR-/tmp}/.$app_name.bin.nid
-notify=false
+should_notify=false
+is_output=true
 
 true()  { return 0; }
 false() { ! true;   }
@@ -33,6 +34,30 @@ Usage: $app_name [options] [-|+]<value>[%]
 EOF
   exit "$err"
 }
+notify() {
+  _notify_icon=notification
+  $is_output && \
+    _notify_icon=$_notify_icon-audio-volume || \
+    _notify_icon=$_notify_icon-microphone-sensitivity
+  _notify_icon=$_notify_icon-high
+  notify-send.sh \
+    --urgency normal \
+    --expire-time 3000 \
+    --app-name "$app_name" \
+    --icon $_notify_icon \
+    --replace-file "$nid_file" \
+    "$@"
+  unset _notify_icon
+}
+check_avail() {
+  if ! command -v "$1" >/dev/null; then
+    echo >&2 "Missing dependency: $1"
+    $should_notify && notify "Missing dependency: $1"
+    false
+  else
+    true
+  fi
+}
 
 [ -f "$lock_file" ] && exit
 touch "$lock_file" && trap 'rm -f "$lock_file"' EXIT HUP INT TERM
@@ -40,15 +65,14 @@ touch "$lock_file" && trap 'rm -f "$lock_file"' EXIT HUP INT TERM
 # input parsing and validation
 [ $# -gt 0 ] || usage 1
 
-output=true
 while [ $# -gt 0 ]; do
   case $1 in
     -h|--help) usage ;;
 
-    --notify) notify=true ;;
+    --notify) should_notify=true ;;
 
-    -i|--input)  output=false ;;
-    -o|--output) output=true  ;;
+    -i|--input)  is_output=false ;;
+    -o|--output) is_output=true  ;;
 
     -m|--mute)   mute=true   ;;
     -u|--unmute) mute=false  ;;
@@ -59,7 +83,10 @@ while [ $# -gt 0 ]; do
   shift
 done
 
-$output && target=sink || target=source
+check_avail pactl || exit 1
+check_avail pacmd || exit 1
+
+$is_output && target=sink || target=source
 TARGET=$(echo $target | tr '[:lower:]' '[:upper:]')
 
 if [ $# -gt 0 ]; then
@@ -72,7 +99,7 @@ if [ $# -gt 0 ]; then
 fi
 [ -n "$mute" ] && pactl set-$target-mute "@DEFAULT_$TARGET@" $mute
 
-$notify || exit 0
+$should_notify || exit 0
 
 # query values for notification
 index=$(pacmd list-${target}s | grep -A0 '\* index:')
@@ -90,7 +117,7 @@ muted=$(echo "$data" | grep Mute:)
 muted=${muted#*: }
 
 icon=notification
-if $output; then
+if $is_output; then
   label="Output volume"
   icon=$icon-audio-volume
 else
@@ -117,11 +144,8 @@ case $muted in
 esac
 
 pgrep -xu "$USER" pactl || pkill -RTMIN+25 i3blocks
-notify-send.sh \
-  --app-name "$app_name" \
+notify \
   --urgency $urgency \
-  --expire-time 3000 \
   --icon $icon \
   --hint int:value:"$volume" \
-  --replace-file "$nid_file" \
   "$summary" "$description"
