scripts: manage notif. id in wrapper, misc. tweaks

diff --git a/.config/sway/scripts/idler b/.config/sway/scripts/idler
--- a/.config/sway/scripts/idler
+++ b/.config/sway/scripts/idler
@@ -6,7 +6,7 @@ SUSPEND=900
 
 usage() {
    cat<<USAGE
-${0##*/} [OPTIONS...]
+$(basename "$0") [OPTIONS...]
 
 Options:
   -h,--help            Shows this message and exists.
@@ -20,40 +20,40 @@ USAGE
 }
 
 die() {
-   echo "$@" >&2
-   exit 1
+  echo "$@" >&2
+  exit 1
 }
 
 set_timeout() {
-   case $2 in
-      *[![:digit:]]*) die "Invalid timeout, not a number: $2" ;;
-      -*|0) die "Invalid timeout, not positive: $2" ;;
-      *) ;;
-   esac
-   eval "$1=$2"
+  case $2 in
+    *[![:digit:]]*) die "Invalid timeout, not a number: $2" ;;
+    -*|0) die "Invalid timeout, not positive: $2" ;;
+    *) ;;
+  esac
+  eval "$1=$2"
 }
 
 while [ $# -gt 0 ]; do
-   case $1 in
-      --lock|--blank|--suspend)
-         TIMEOUT=$(echo "${1#--}" | awk '{ print(toupper($0)) }')
-         shift
-         set_timeout "$TIMEOUT" "$1"
-         ;;
-      -h|--help) usage; exit ;;
-      *) die "Unknown argument: $1" ;;
-   esac
-   shift
+  case $1 in
+    --lock|--blank|--suspend)
+      TIMEOUT=$(echo "${1#--}" | awk '{ print(toupper($0)) }')
+      shift
+      set_timeout "$TIMEOUT" "$1"
+      ;;
+    -h|--help) usage; exit ;;
+    *) die "Unknown argument: $1" ;;
+  esac
+  shift
 done
 
 pkill swayidle # override current if re-running
 swayidle -w \
-   timeout $LOCK             'swaylock -f' \
-   timeout $((LOCK + BLANK)) 'swaymsg "output * power off"' \
-    resume                   'swaymsg "output * power on"' \
-   \
-   timeout $BLANK 'pgrep swaylock && swaymsg "output * power off"' \
-    resume        'pgrep swaylock && swaymsg "output * power on"' \
-   \
-   timeout $SUSPEND 'systemctl suspend' \
+  timeout $LOCK             'swaylock -f' \
+  timeout $((LOCK + BLANK)) 'swaymsg "output * power off"' \
+   resume                   'swaymsg "output * power on"' \
+  \
+  timeout $BLANK 'pgrep swaylock && swaymsg "output * power off"' \
+  resume         'pgrep swaylock && swaymsg "output * power on"' \
+  \
+  timeout $SUSPEND 'systemctl suspend' \
   before-sleep 'swaylock -f'
diff --git a/.local/bin/notify-send b/.local/bin/notify-send
--- a/.local/bin/notify-send
+++ b/.local/bin/notify-send
@@ -1,1 +1,47 @@
-notify-send.sh
+#!/bin/sh
+# A wrapper around `notify-send` that
+
+CMD=notify-send
+NOTIFY=$(command -v -p $CMD)
+if [ -z "$NOTIFY" ]; then
+  # let the shell handle the missing binary
+  exec $CMD
+fi
+
+process_args() {
+  while [ $# -gt 0 ]; do
+    case $1 in
+      --app-name|--app-name=*)
+        APP_NAME=${1#*=}
+        [ "$APP_NAME" = "$1" ] && APP_NAME=$2
+        ;;
+      -[!-]a) APP_NAME=$2 ;;
+      --help|-*\?*) exec $NOTIFY --help ;;
+    esac
+    shift
+  done
+}
+process_args "$@"
+
+if [ -n "$APP_NAME" ]; then
+  NID_FILE=${XDG_RUNTIME_DIR-/tmp}/.$APP_NAME.nid
+  OLD_NID=$(cat "$NID_FILE")
+fi
+
+NID=$($NOTIFY \
+  --replace-id "${OLD_NID:-0}" \
+  --print-id \
+  "$@")
+
+case $NID in
+  *[![:digit:]]*)
+    echo "Invalid notification id: $NID"
+    exit 254
+    ;;
+esac
+
+[ -n "$NID" ] || exit 0
+
+mkdir -p "$(dirname "$NID_FILE")"
+touch -a "$NID_FILE"
+printf '%s' "$NID" > "$NID_FILE"
