shrc: Get around to "fixing" copy/paste functions

diff --git a/.shell/rc b/.shell/rc
--- a/.shell/rc
+++ b/.shell/rc
@@ -188,18 +188,22 @@ if command -v xclip >/dev/null; then
       tmp=$(mktemp)
       # shellcheck disable=SC2064
       trap "rm -rf $tmp" EXIT HUP INT TERM
-      touch "$tmp"
+      while read -r line; do
+        echo "$line" >> "$tmp"
+      done
     fi
 
     input=${tmp-$1}
+    unset tmp
     if command -v xdg-mime >/dev/null; then
       ft=$(xdg-mime query filetype "$input" 2>&-)
     else
-      echo "Cannot infer MIME type for '$input', assuming plain text"
+      echo >&2 "Cannot infer MIME type for '$input', assuming plain text"
+      ft=text/plain
     fi
-    xclip -t "${ft-text/plain}" -selection clipboard -i "$input"
+    xclip -t "$ft" -selection clipboard -i "$input"
   }
-  paste() { xclip -selection clipboard -o "$1"; }
+  paste() { xclip -selection clipboard -o "$1" ; }
 fi
 
 # where were we?
